name: ServerGuard
version: 1.26.1.2
main: pl.serverguard.ServerGuard
api-version: '1.21'
description: "Monitoring serwera - komendy, skrzynie, bloki, panel GUI."
authors: [ServerGuard]

softdepend:
  - BellHub

commands:
  sg:
    description: Panel administracyjny ServerGuard
    usage: /sg [gui|reload|help]
    permission: serverguard.admin
  sghistory:
    description: Historia gracza
    usage: /sghistory <nick> [komendy|skrzynie|bloki] [ilosc]
    permission: serverguard.admin
  sgsearch:
    description: Szukaj w logach
    usage: /sgsearch <fraza>
    permission: serverguard.admin

permissions:
  serverguard.admin:
    description: Dostep do komend ServerGuard
    default: op
  serverguard.notify:
    description: Otrzymuje alerty o probach uzycia komend admina
    default: op
  serverguard.bypass:
    description: Pomija logowanie komend gracza
    default: false
  serverguard.audit.bypass:
    description: Pomija audyt i blokade komend admina
    default: false
